version: "3"
services:

  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"


  car:
    image: car
    build: ./cars/
    depends_on:
      - postgres
    environment:
      - APPLICATION_PORT=8070
      - APPLICATION_NAME=car
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - "8070:8070"


  payment:
    image: payment
    build: ./payment/
    depends_on:
      - car
    environment:
      - APPLICATION_PORT=8050
      - APPLICATION_NAME=payment
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - "8050:8050"


  rental:
    image: rental
    build: ./rental/
    depends_on:
      - car
      - payment
    environment:
      - APPLICATION_PORT=8060
      - APPLICATION_NAME=rental
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - "8060:8060"


  gateway:
    image: gateway
    build: ./gateway/
    depends_on:
      - rental
    environment:
      - APPLICATION_PORT=8080
      - APPLICATION_NAME=gateway
    ports:
      - "8080:8080"


#    external-api
#    2f5c4bfcfbd63451146a47c778874be3a1ba71382521efa12dbee9bf85fdb85d