apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  20-create-db.sql: |
    CREATE TABLE cars(
    id                  SERIAL PRIMARY KEY,
    car_uid             uuid UNIQUE NOT NULL,
    brand               VARCHAR(80) NOT NULL,
    model               VARCHAR(80) NOT NULL,
    registration_number VARCHAR(20) NOT NULL,
    power               INT,
    price               INT         NOT NULL,
    type                VARCHAR(20)
    CHECK (type IN ('SEDAN', 'SUV', 'MINIVAN', 'ROADSTER')),
    availability        BOOLEAN     NOT NULL
    );
    
    CREATE TABLE payment
    (
    id          SERIAL PRIMARY KEY,
    payment_uid uuid        NOT NULL,
    status      VARCHAR(20) NOT NULL
    CHECK (status IN ('PAID', 'CANCELED')),
    price       INT         NOT NULL
    );
    
    CREATE TABLE rental
    (
    id          SERIAL PRIMARY KEY,
    rental_uid  uuid UNIQUE              NOT NULL,
    username    VARCHAR(80)              NOT NULL,
    payment_uid uuid                     NOT NULL,
    car_uid     uuid                     NOT NULL,
    date_from   TIMESTAMP WITH TIME ZONE NOT NULL,
      date_to     TIMESTAMP WITH TIME ZONE NOT NULL,
    status      VARCHAR(20)              NOT NULL
    CHECK (status IN ('IN_PROGRESS', 'FINISHED', 'CANCELED'))
      );
    
    alter table cars
    owner to postgres;
    
    alter table payment
    owner to postgres;
    
    alter table rental
    owner to postgres;
    
    
    INSERT INTO cars (id, availability, brand, car_uid, model, power, price, registration_number, type)
    values (1, true, 'Mercedes Benz', '109b42f3-198d-4c89-9276-a7520a7120ab', 'GLA 250', 249, 3500, 'ЛО777Х799', 'SEDAN')
