car:
  service:
    type: ClusterIP
    port: 8070
    image: v1v55/car
    env:
      APPLICATION_PORT: 8070
      APPLICATION_NAME: car
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

payment:
  service:
    type: ClusterIP
    port: 8050
    image: v1v55/payment
    env:
      APPLICATION_PORT: 8050
      APPLICATION_NAME: payment
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

rental:
  service:
    type: ClusterIP
    port: 8060
    image: v1v55/rental
    env:
      APPLICATION_PORT: 8060
      APPLICATION_NAME: rental
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

gateway:
   service:
    type: NodePort
    port: 8080
    nodePort: 30000
    image: v1v55/gateway
    env:
      APPLICATION_PORT: 8080
      APPLICATION_NAME: gateway